apiVersion: v1 
kind: ConfigMap 
metadata:
  name: ps-config
  namespace: psns
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/artgallery"
  PORT: "3000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
