apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels: 
      app: {{ .Values.deployment.labels.app }}
  template: 
    metadata:
      labels: 
        app: {{ .Values.deployment.labels.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: MONGODB_URI
            value: "mongodb://mongodb-service.{{ .Release.Namespace }}.svc.cluster.local:27017"
          ports: 
            - containerPort: {{ .Values.deployment.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" .Release.Name .Values.configMapRef.configmapname }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
      volumes:
        - name: {{ .Values.volumeMounts.name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" .Release.Name .Values.persistence.app.claimName }}
