apiVersion: v1
kind: Pod
metadata: 
  name: {{ .Release.Name }}-pod
  namespace: {{ .Values.namespace }}
spec: 
  containers: 
    - name: {{ .Values.deployment.containerName}}
      image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
      ports:
        - containerPort: {{ .Values.deployment.containerPort}}