apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ps-deployment
  namespace: psns
spec: 
  replicas: 5
  selector: 
    matchLabels: 
      app: ps
  template: 
    metadata:
      labels: 
        app: ps
    spec:                     # <-- correct level
      containers:
        - name: pscont
          image: amritha1989/photostudio:latest
          env:
          - name: MONGO_URI
            value: "mongodb://mongodb-service:27017/artgallery"
          ports: 
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ps-config
          volumeMounts:
            - name: ps-storage
              mountPath: /app/storage   # Change to your desired path

      # Define the volume that references your PVC
      volumes:
        - name: ps-storage
          persistentVolumeClaim:
            claimName: ps-pvc