# mongodb-secret-stringdata.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-mongodb-secret
  namespace: {{ .Values.namespace}}
type: {{ .Values.db.secretType}}
stringData:
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}