apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ps-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- range .Values.persistence.app.accessModes }}
        - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.persistence.app.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.app.size }}