apiVersion: v1
kind: Service
metadata:
  name: ps-service
  namespace: ps-ns
spec:
  selector:
    app: ps
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30089 
  type: LoadBalancer
