apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    {{- range .Values.persistence.mongodb.dbaccessModes }}
        - {{ . }}
    {{- end }}
  storageClassName: {{ .Values.persistence.mongodb.dbstorageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.mongodb.dbsize }}